version: '3.8'
services:
  catatan-app-dev:
    container_name: catatan-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/catatan-app'
      - '/catatan-app/node_modules'
    expose:
      - 3000:3000
    command: npx vite --host 0.0.0.0 --port 3000